'use client';

import '@rainbow-me/rainbowkit/styles.css';
import '@/app/globals.css';
import 'react-toastify/dist/ReactToastify.css';

// import type { Metadata } from 'next'
import { Inter } from 'next/font/google';
import { LocalizationProvider } from '@mui/x-date-pickers';
import { AdapterDayjs } from '@mui/x-date-pickers/AdapterDayjs';
import { CssBaseline } from '@mui/material';
import { WagmiConfig } from 'wagmi';
import {
  RainbowKitProvider,
  darkTheme,
  lightTheme,
} from '@rainbow-me/rainbowkit';
import { ToastContainer } from 'react-toastify';

import ThemeProviderWrapper from '@/theme/ThemeProvider';
import { SidebarProvider } from '@/contexts/SidebarContext';
import { SearchFiltersProvider } from '@/contexts/SearchFiltersContext';
import { chains, wagmiConfig } from '@/lib/wagmi';

const inter = Inter({ subsets: ['latin'] });

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProviderWrapper>
          <WagmiConfig config={wagmiConfig}>
            <RainbowKitProvider
              theme={{
                lightMode: lightTheme({
                  accentColor: 'black',
                  borderRadius: 'small',
                  overlayBlur: 'small',
                }),
                darkMode: darkTheme({
                  borderRadius: 'small',
                  overlayBlur: 'small',
                }),
              }}
              chains={chains}
            >
              <SidebarProvider>
                <SearchFiltersProvider>
                  <LocalizationProvider dateAdapter={AdapterDayjs}>
                    <CssBaseline />
                      {children}
                      <ToastContainer position='bottom-left' autoClose={6000}  />
                  </LocalizationProvider>
                </SearchFiltersProvider>
              </SidebarProvider>
            </RainbowKitProvider>
          </WagmiConfig>
        </ThemeProviderWrapper>
      </body>
    </html>
  );
}
